---
- name: httpd service
  hosts: localhost

  tasks:

  - name: apache web service
    yum:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started

~
